/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../MCAL/RCC/RCC_Interface.h"
#include "../MCAL/GPIO/GPIO_Interface.h"

int main(void)
{
	RCC_Init();
	RCC_PeripheralEnable(RCC_IOPA_EN);
	/*
	RCC_PeripheralDisable(RCC_IOPA_EN);
	*/
	GPIO_Config_t led;

	led.mode = GPIO_MODE_INPUT_PU_PD;

    while (1)
    {

    }
}
